#13/feat/add login and dashboard
xction-dev/xflix pull request #16
Opened 2023-08-17 18:12 UTC by nuagenic

# 요약
| 담당자 | 시작일 | 마감일 | 관련 이슈 |
|------|------|-----------|-----------|
| 백창인 | 23-08-17 | 23-08-18 |   |

# 관련 이슈

#13 

# 체크리스트
### PR 달 때
- [ ] Enhancement나 Fix 라벨을 달았나요?
- [ ] Review를 요청했나요?
- [ ] `yarn build`로 테스트를 했나요?

### 머지하기 전에
- [ ] 리뷰 코멘트를 모두 해결했나요?
- [ ] squash merge 임을 확인했나요?

# 작업 내용
- login과 dashboard 페이지 만들고, issue 지시 사항 모두 완료 했습니다.
- play 폴더는 라우팅 위해 만들어 두었습니다.

# 논의가 필요한 사항
- 라우팅을 위한 페이지는 ex) app/dashboard/page.js로 만들고, 그 안에 담을 component들을 따로 components 폴더를 만들어 관리했습니다. 이런 방식이 맞을까요? 개선 필요한 지점 있다면 알려주시면 감사하겠슴다
- 현재 IDInput과 PWInput의 경우 각각 다른 컴포넌트로 관리하고 있는데, 겹치는 코드가 많아 하나로 합치는 게 좋을지, 아니면 그대로 둘지 의견 구합니다.
- 현재 id와 pw 저장하는 useState는 각각 IDInput과 PWInput에 선언되어 있는데, 이게 좋을까요?(왠지 아닐듯). 상위에 선언하고 props로 내려주면 좋을 것 같은데, 어디까지 상위로 올라가는 게 좋을지 몰라 의견 구합니다.
- 라우팅되는 버튼의 경우, next에서 제공하는 Link 태그로 감싸는 형태로 작업했습니다. 이 때문에 Curations.js에서 key 값을 Link 태그에 줘야 되던데, 이게 좀 찜찜해서... 괜찮은가요?
- Curations는 carousel과 card components로 나누지 않고 하나로 퉁쳐서 작업했는데, 나누는 게 좋을지 의견 구합니다.

- c.f) PR 기본 템플릿에 |-----|가 하나 더 있어서 표 적용이 자동으로 안 되는 것 같습니다!

2023-08-20 11:31 UTC, designDefined requested changes
코멘트로는 사소한 코드 스타일 관련한 내용들 달아놨어!
코멘트 단 거 한 번 확인해보고, 회의 때 이야기한 컴포넌트 디렉토리 정리하기, 컴포넌트 분리, useState 옮기기 등등 재작업해서 머지합시다~~

2023-08-20 11:31 UTC, designDefined commented on src/components/Curations/Curations.css
> +    /* border: 1px solid black; */
헷갈릴 수 있으니 주석은 지우거나 디버깅용이라고 이름달기

2023-08-20 11:31 UTC, designDefined commented on src/components/Curations/Curations.js
> +        </div>
언급한 것처럼 컴포넌트 추출할 수 있으면 최대한 추출해봅시다!

2023-08-20 11:31 UTC, designDefined commented on src/components/Header/Header.js
> +            </Link>
```suggestion
            <Link href="/login" className="login-btn">
                로그인
            </Link>
```

<Link/>가 이미 a 태그이기 때문에 안에 버튼을 굳이 넣을 필요는 없을 듯...!

2023-08-20 11:31 UTC, designDefined commented on src/components/Curations/Curations.js
> +                                    <Link href={'/play/' + content.id} style={{ textDecoration: "none", color: "black"}}>
key 넣는거 까먹지 않기

2023-08-20 11:31 UTC, designDefined commented on src/components/Curations/Curations.js
> +                                content.type == "youtube" ? // content.type이 youtube이면 play/${id}로 라우팅, writing이면 url 이동
```suggestion
                                isPlayable(content) ? // content.type이 youtube이면 play/${id}로 라우팅, writing이면 url 이동
```

회의 때 말한 것처럼 isPlayable 같은 함수를 전역으로 export 해서 사용하면, 이런 데에도 같은 로직을 이용할 수 있을듯!

2023-08-20 11:31 UTC, designDefined commented on src/components/Login/IDInput/IDInput.js
> +    const [ inputValue, setInputValue ] = useState('')
회의 때 말한 것처럼 state를 부모로 빼봅시다

2023-08-20 11:31 UTC, designDefined commented on src/components/Login/IDInput/IDInput.js
> +    })
onChange 내부의 화살표 함수가 낫지 않을까?

또 이런 함수 최적화에 관해서는 [useCallback](https://react.dev/reference/react/useCallback) api 나중에 공부해봐도 낫밷

2023-08-20 11:31 UTC, designDefined commented on src/components/Login/IDInput/IDInput.js
> +        </div>
요것도 fragment로 바꿀 수 있긴... 하지만, 때로는 컴포넌트를 div로 묶는 게 나을 수도... 딱히 스타일링 할 게 없다면 코드 가독성의 문제인 것 같음

2023-08-20 11:31 UTC, designDefined commented on src/components/Login/LoginContainer/LoginContainer.css
> +    margin-top: 0;
h2 기본 margin을 초기화해준건가? h1~h4, ul, ol 등에 붙은 margin은 전역으로 초기화해줄 때도 있으니 궁금하면 css-reset으로 검색 ㄱㄱ

2023-08-20 11:31 UTC, designDefined commented on src/components/SubmitButton/SubmitButton.js
> +            <button className="submit-btn">확인</button>
상동

2023-08-21 12:09 UTC, nuagenic commented on src/components/Curations/Curations.css
> +    margin: 0 0 0 40px;
margin-left만 설정하려고 한 거라 margin-left로 바꿨습니다~

2023-08-22 10:24 UTC, nuagenic commented on src/components/Login/LoginContainer/LoginContainer.css
> +    margin-top: 0;
@designDefined  우선 저 부분은 h2의 나머지 margin은 두고, 헤더 바로 아래에서 <LoginContainer />를 시작하고 싶어서 margin-top만 조정해준 코드입니다!
css-reset 찾아봤는데, 다른 컴포넌트에서도 h1~h6의 기본값 크기와 margin을 사용하고 있어서, 우선은 그대로 두겠습니다! css normalize도 찾아봤는데 그 경우는 어차피 제가 의도한 바를 따르려면 margin-top: 0을 주어야 하는 것 같구요. 혹시 css reset 작업이 필요하면 말씀 주세요!

2023-08-22 10:26 UTC, nuagenic commented on src/components/Login/IDInput/IDInput.js
> +        </div>
흠 일단 어떻게 할지 잘 모르겠어서 그대로 두겠습니다! 코드 가독성의 문제라는 게, <div>가 붙은 태그가 아무 className 없이 그냥 사용되도록 짜여진 코드 구조가 문제라는 건가요??

2023-08-22 11:48 UTC, nuagenic commented on src/components/Curations/Curations.js
> +        </div>
- 전체 뼈대를 잡는 DashboardContainer.js
- Curation별로 Content 목록을 보여주는 Carousel.js
- 각 Carousel에 들어있는 ContentCard.js
형태로 재편했습니다. 

<확인 바랍니다>
1. 이때 curations.json을 DashboardContainer에서 받아와서 props로 내려주고 있는데, 이렇게 하면 될까요?
2. Carousel.js에서 ContentCard.js로 줄 때는 현재 content를 통으로 내려주고 있는데, props를 많이 만들어서 (예: <ContentCard id={content.id} thumbnail={content.thumbnail} />) ContentCard.js를 깔끔하게 보이는 게 맞나요? 아니면 현재 코드가 더 바람직한가요?

2023-08-22 11:53 UTC, nuagenic commented on src/components/Curations/Curations.js
> +                                content.type == "youtube" ? // content.type이 youtube이면 play/${id}로 라우팅, writing이면 url 이동
src/utils에 isPlayable.js로 함수 생성했는데, 이렇게 하면 되는지 확인 부탁드립니다!

2023-08-23 10:02 UTC, designDefined commented on src/components/Login/IDInput/IDInput.js
> +        </div>
음 만약 fragment로 쌓여있는 컴포넌트가 html로 파싱될 경우 <h5>와 <input> 태그가 평행하게 놓이게 되는데, 치자면 h5는 input의 제목이니까 둘을 하나의 태그 안에 묶는 게 더 예쁜(?) html 구조가 아닐까 하는 의미였어! 

예를 들어 fragment로 묶은 IDInput 컴포넌트를 여러 개 쭉 배치할 경우
```
<h5>ID</h5>
<input type="text" />
<h5>Password</h5>
<input type="password" />
<h5>이메일</h5>
<input type="text" />
```
html은 이런 모양이 되는데, 그럼 뭐가 뭐의 제목인지 잘 안보인단 말이지
그보다는
```
<div>
  <h5>ID</h5>
  <input type="text" />
</div>
<div>
  <h5>Password</h5>
  <input type="password" />
</div>
```
요렇게 생기는 게 좀 더 직관적이잖아? 그런 의미에서 빈 div는 잘 쓰지 않지만, 이런 경우에는 써주는게 좋을 수 있다 하는 생각...

2023-08-23 10:02 UTC, designDefined commented on src/components/Login/LoginContainer/LoginContainer.css
> +    margin-top: 0;
오키오키 css reset은 프로젝트 단위에서 적용하다보니 다른 작업자랑도 얘기를 해봐야해서, 다음 회의때 같이 얘기해보고 그 때 적용하자!

2023-08-23 10:03 UTC, designDefined commented on src/components/Curations/Curations.js
> +                                content.type == "youtube" ? // content.type이 youtube이면 play/${id}로 라우팅, writing이면 url 이동
굿굿! 요거 승현이랑도 얘기해서 승현이 부분에서도 쓸 수 있게 해보자

2023-08-23 10:04 UTC, designDefined commented on src/components/Curations/Curations.js
> +        </div>
요거는 오늘밤에 답변달겠음ㅠ

2023-08-23 15:20 UTC, designDefined commented on src/components/Curations/DashboardContainer/DashboardContainer.js
> +                </div>
여기가 좀 고민되는 부분인데, 일단 `<div>`나 `<h3>`도 모두 Carousel 안에 넣어서 Carousel 컴포넌트를 만드는 게 좀 더 일반적인 방법일 것 같으...! 아무래도 캐러셀의 제목 서식을 바꾸는 등의 수정을 진행할 때 `Carousel.js` 파일을 건드는 것이 일반적일 것 같은데, 지금은 DashboardContainer를 건드려야 하니까, 좀 헷갈릴 수 있달까?

물론 지금처럼 컴포넌트를 나누면 제목이 없는 Carousel에도 같은 컴포넌트를 재사용할 수 있다는 것이 장점이지만, 당장은 그런 장점이 드러나지는 않을듯...!

뭐가 정답이다 하는 것은 없으니, 한 번 고민ㄱㄱ

2023-08-23 19:12 UTC, merged